name: Lint, test, and build
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-test-build:
    strategy:
      matrix:
        vars: [
          {os: ubuntu-24.04, platform: linux/amd64},
          {os: ubuntu-24.04-arm, platform: linux/arm64}
        ]

    name: Lint, test, and build the code
    runs-on: ${{ matrix.vars.os }}
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker buildx for multi-architecture builds
        uses: docker/setup-buildx-action@v3
        with:
          use: true

      - name: Install Skopeo # For some reason required by devcontainers/ci
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo

      - name: Prepare devcontainer-ci.json
        run: |
          rm -f .devcontainer/devcontainer.json
          mv .devcontainer/devcontainer-ci.json .devcontainer/devcontainer.json

      - name: Run lint, test, and build
        uses: devcontainers/ci@v0.3
        with:
          push: never
          platform: ${{ matrix.vars.platform }}
          runCmd: >
            npm install && \
            go mod download && \
            task fixperms && \
            task check-deps && \
            task lint-only && \
            task test-only && \
            task build
