name: Lint, test, and build
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-test-build:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    
    name: Lint, test, and build the code
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run lint, test, and build
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: |
            npm install
            go mod download
            task fixperms
            task check-deps
            task lint-only
            task test-only
            task build
